[package]
name = "ultra_omega"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.174"
omega = { path = "../omega" }
ovp = { path = "../ovp" }

[lib]
crate-type = ["rlib", "cdylib"]

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = 3