[package]
name = "ultra_omega"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.173"
omega = { path = "../omega" }
serde_json = "1.0.140"
sha2 = "0.10.8"

[lib]
name = "ultra_omega" # The name of your library crate
path = "src/lib.rs"

[[bin]]
name = "test-harness" # The name you'll use to run the binary
path = "src/bin/test_harness.rs"